name: FAIR-BioRS-code
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.7
  - ipykernel = 6.2.0
  - openpyxl = 3.0.10
  - yaml = 0.2.5
  - ipywidgets
  - pip
  - pip:
      - pandas == 1.3.2
      - matplotlib == 3.0.3
      - seaborn == 0.11.2
      - pygithub == 1.55
