name: env-FAIR-BioRS-code
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.7
  - ipykernel = 6.2.0
  - ipywidgets
  - pip
  - pip:
      - pandas == 1.3.2
      - openpyxl == 3.0.7
